export const placeTypeEnum = {
  TERRITORY: 1,
  WATER: 2,
};

export const placeList = {
  'Boh': {country: 'Austria', fullName: 'Bohemia', type: placeTypeEnum.TERRITORY},
  'Bud': {country: 'Austria', fullName: 'Budapest', type: placeTypeEnum.TERRITORY},
  'Gal': {country: 'Austria', fullName: 'Galicia', type: placeTypeEnum.TERRITORY},
  'Tri': {country: 'Austria', fullName: 'Trieste', type: placeTypeEnum.TERRITORY},
  'Tyr': {country: 'Austria', fullName: 'Tyrolia', type: placeTypeEnum.TERRITORY},
  'Vie': {country: 'Austria', fullName: 'Vienna', type: placeTypeEnum.TERRITORY},

  'Cly': {country: 'England', fullName: 'Clyde', type: placeTypeEnum.TERRITORY},
  'Edi': {country: 'England', fullName: 'Edinburgh', type: placeTypeEnum.TERRITORY},
  'Lvp': {country: 'England', fullName: 'Liverpool', type: placeTypeEnum.TERRITORY},
  'Lon': {country: 'England', fullName: 'London', type: placeTypeEnum.TERRITORY},
  'Wal': {country: 'England', fullName: 'Wales', type: placeTypeEnum.TERRITORY},
  'Yor': {country: 'England', fullName: 'Yorkshire', type: placeTypeEnum.TERRITORY},

  'Bre': {country: 'France', fullName: 'Bretagne', type: placeTypeEnum.TERRITORY},
  'Bur': {country: 'France', fullName: 'Burgundy', type: placeTypeEnum.TERRITORY},
  'Gas': {country: 'France', fullName: 'Gascony', type: placeTypeEnum.TERRITORY},
  'Mar': {country: 'France', fullName: 'Marseilles', type: placeTypeEnum.TERRITORY},
  'Par': {country: 'France', fullName: 'Paris', type: placeTypeEnum.TERRITORY},
  'Pic': {country: 'France', fullName: 'Picardy', type: placeTypeEnum.TERRITORY},

  'Ber': {country: 'Germany', fullName: 'Berlin', type: placeTypeEnum.TERRITORY},
  'Kie': {country: 'Germany', fullName: 'Kiel', type: placeTypeEnum.TERRITORY},
  'Mun': {country: 'Germany', fullName: 'Munich', type: placeTypeEnum.TERRITORY},
  'Pre': {country: 'Germany', fullName: 'Prussia', type: placeTypeEnum.TERRITORY},
  'Ruh': {country: 'Germany', fullName: 'Ruhr', type: placeTypeEnum.TERRITORY},
  'Sil': {country: 'Germany', fullName: 'Silesia', type: placeTypeEnum.TERRITORY},

  'Apu': {country: 'Italy', fullName: 'Apulia', type: placeTypeEnum.TERRITORY},
  'Nap': {country: 'Italy', fullName: 'Naples', type: placeTypeEnum.TERRITORY},
  'Pie': {country: 'Italy', fullName: 'Piedmont', type: placeTypeEnum.TERRITORY},
  'Rom': {country: 'Italy', fullName: 'Rome', type: placeTypeEnum.TERRITORY},
  'Tus': {country: 'Italy', fullName: 'Tuscany', type: placeTypeEnum.TERRITORY},
  'Ven': {country: 'Italy', fullName: 'Venice', type: placeTypeEnum.TERRITORY},

  'Fin': {country: 'Russia', fullName: 'Finland', type: placeTypeEnum.TERRITORY},
  'Lvn': {country: 'Russia', fullName: 'Livonia', type: placeTypeEnum.TERRITORY},
  'Mos': {country: 'Russia', fullName: 'Moscow', type: placeTypeEnum.TERRITORY},
  'Sev': {country: 'Russia', fullName: 'Sevastopol', type: placeTypeEnum.TERRITORY},
  'StP': {country: 'Russia', fullName: 'St. Petersburg', type: placeTypeEnum.TERRITORY},
  'Ukr': {country: 'Russia', fullName: 'Ukraine', type: placeTypeEnum.TERRITORY},
  'War': {country: 'Russia', fullName: 'Warsaw', type: placeTypeEnum.TERRITORY},

  'Ank': {country: 'Turkey', fullName: 'Ankara', type: placeTypeEnum.TERRITORY},
  'Arm': {country: 'Turkey', fullName: 'Armenia', type: placeTypeEnum.TERRITORY},
  'Con': {country: 'Turkey', fullName: 'Constantinople', type: placeTypeEnum.TERRITORY},
  'Smy': {country: 'Turkey', fullName: 'Smyrna', type: placeTypeEnum.TERRITORY},
  'Syr': {country: 'Turkey', fullName: 'Syria', type: placeTypeEnum.TERRITORY},

  'Alb': {country: 'Albania', fullName: 'Albania', type: placeTypeEnum.TERRITORY},
  'Bel': {country: 'Belgium', fullName: 'Belgium', type: placeTypeEnum.TERRITORY},
  'Bul': {country: 'Bulgaria', fullName: 'Bulgaria', type: placeTypeEnum.TERRITORY},
  'Den': {country: 'Denmark', fullName: 'Denmark', type: placeTypeEnum.TERRITORY},
  'Gre': {country: 'Greece', fullName: 'Greece', type: placeTypeEnum.TERRITORY},
  'Hol': {country: 'Holland', fullName: 'Holland', type: placeTypeEnum.TERRITORY},
  'Nwy': {country: 'Norway', fullName: 'Norway', type: placeTypeEnum.TERRITORY},
  'NAf': {country: 'North Africa', fullName: 'North Africa', type: placeTypeEnum.TERRITORY},
  'Por': {country: 'Portugal', fullName: 'Portugal', type: placeTypeEnum.TERRITORY},
  'Rum': {country: 'Rumania', fullName: 'Rumania', type: placeTypeEnum.TERRITORY},
  'Ser': {country: 'Servia', fullName: 'Servia', type: placeTypeEnum.TERRITORY},
  'Spa': {country: 'Spain', fullName: 'Spain', type: placeTypeEnum.TERRITORY},
  'Swe': {country: 'Sweden', fullName: 'Sweden', type: placeTypeEnum.TERRITORY},
  'Tun': {country: 'Tunis', fullName: 'Tunis', type: placeTypeEnum.TERRITORY},

  'Adr': {fullName: 'Adriatic Sea', type: placeTypeEnum.WATER},
  'Aeg': {fullName: 'Aegean Sea', type: placeTypeEnum.WATER},
  'Bal': {fullName: 'Baltic Sea', type: placeTypeEnum.WATER},
  'Bar': {fullName: 'Barents Sea', type: placeTypeEnum.WATER},
  'Bla': {fullName: 'Black Sea', type: placeTypeEnum.WATER},
  'Eas': {fullName: 'Eastern Mediterranean', type: placeTypeEnum.WATER},
  'Eng': {fullName: 'English Channel', type: placeTypeEnum.WATER},
  'Bot': {fullName: 'Gulf of Bothnia', type: placeTypeEnum.WATER},
  'GoL': {fullName: 'Gulf of Lyon', type: placeTypeEnum.WATER},
  'Hel': {fullName: 'Helgoland Bight', type: placeTypeEnum.WATER},
  'Ion': {fullName: 'Ionian Sea', type: placeTypeEnum.WATER},
  'Iri': {fullName: 'Irish Sea', type: placeTypeEnum.WATER},
  'Mid': {fullName: 'Mid-Atlantic Ocean', type: placeTypeEnum.WATER},
  'NAt': {fullName: 'North Atlantic Ocean', type: placeTypeEnum.WATER},
  'Nth': {fullName: 'North Sea', type: placeTypeEnum.WATER},
  'Nrg': {fullName: 'Norwegian Sea', type: placeTypeEnum.WATER},
  'Ska': {fullName: 'Skagerrak', type: placeTypeEnum.WATER},
  'Tyn': {fullName: 'Tyrrhenian Sea', type: placeTypeEnum.WATER},
  'Wes': {fullName: 'Western Mediterranean', type: placeTypeEnum.WATER},
};

export const startingPosition = {
  'Austria': ['Vie', 'Bud', 'Tri'],
  'England': ['Lon', 'Edi', 'Lvp'],
  'France': ['Par', 'Mar', 'Bre'],
  'Germany': ['Ber', 'Mun', 'Kie'],
  'Italy': ['Rom', 'Ven', 'Nap'],
  'Russia': ['Mos', 'Sev', 'War', 'StP'],
  'Turkey': ['Ank', 'Con', 'Smy'],
};
